(define (average x y)
  (/ (+ x y) 2))
(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (make-segment x y)
  (cons x y))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (midpoint-segment segment)
  (cons (average (x-point (start-segment segment)) (x-point (end-segment segment))) (average (y-point (start-segment segment)) (y-point (end-segment segment)))))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define s (make-segment (make-point 1 1) (make-point 3 3)))
(midpoint-segment s)
(print-point (start-segment s))
(print-point (end-segment s))


(define (perimeter-ractangle width length)
  (* (+ width length) 2))
(define (make-rectangle1 a b c)
  (list a b c));输入三个端点，默认a为左下角的点，b为左上角的点，c为右下角的点
(define (make-rectangle2 a b)
  (cons a b));输入长宽
(define (width-rectangle1 r)
  (- (x-point (c-rectangle r)) (x-point (a-rectangle r))))
(define (length-rectangle1)
  (- (y-point (b-rectangle)) (y-point (a-rectangle r))))
(define (width-rectangle2 r)
  (car r))
(define (length-rectangle r)
  (cdr r))
(define (a-rectangle r)
  (car r))
(define (b-rectangle r)
  (car (cdr r)))
(defien (c-rectangle r)
  (car (cdr (cdr r))))